### ISSUE TITLE
Ability to ingest text on command line

### ISSUE THREAD

**Issue by Maijin** [fhightower/ioc-finder#88] opened 2020-09-11 16:38 UTC
Right now you can only pass text as argument but that's not very useful, instead would be nice to be able to do:

`pbpaste | ioc-finder | pbcopy`
or even more simply
`cat doc.txt | ioc-finder`

**Comment by fhightower** [comment] 2020-09-11 20:11
Great idea. I'll get this implemented. This is a duplicate of #69 .

**Comment by Maijin** [comment] 2020-09-11 20:49
haha, I see my bad

**Closed** 2020-09-11 21:19 UTC

**Comment by fhightower** [comment] 2020-09-11 21:30
No problem! It's a great idea that needs to be implemented.

I added this in version 4.0.1 which I just recently shipped to pypi.

**Comment by Maijin** [comment] 2020-09-12 10:20
works like a charm thanks! Sorry I noticed I had never replied to you on ioc-fanger but thanks for those! Very useful 👍
